/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mut.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.mut.MutMod;

public class MutModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MutMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MORE_UPGRADE_TMPLATES = REGISTRY.register("more_upgrade_tmplates",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.mut.more_upgrade_tmplates")).icon(() -> new ItemStack(MutModItems.BLUE_DIAMOND_UPGRADE_TEMPLATE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MutModItems.IRON_ARMOR_REBUILD_TEMPLATE.get());
				tabData.accept(MutModItems.DIAMOND_ARMOR_REBUILD_TEMPLATE.get());
				tabData.accept(MutModItems.STONE_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.IRON_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.GOLD_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.DIAMOND_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.STEEL_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.GILDING_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.OBSIDIAN_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.NETHER_STAR_UPGRADE_TEMPLATE.get());
				tabData.accept(MutModItems.DRAGON_UPGRADE_TEMPLATE.get());
			}).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MORE_UPGRADE_TEMPLATE_EXTRA_ITEMS = REGISTRY.register("more_upgrade_template_extra_items",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.mut.more_upgrade_template_extra_items")).icon(() -> new ItemStack(MutModItems.BLUE_DIAMOND_INGOT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MutModItems.STEEL_INGOT.get());
				tabData.accept(MutModItems.GILDING_INGOT.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_INGOT.get());
				tabData.accept(MutModItems.STEEL_SCRAP.get());
				tabData.accept(MutModItems.DEEP_IRON_SCARP.get());
				tabData.accept(MutModItems.GILDING_SCRAP.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_SCRAP.get());
				tabData.accept(MutModItems.DEEP_IRON_RAW.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_INGOT.get());
				tabData.accept(MutModItems.OBSIDIAN_INGOT.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_INGOT.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_INGOT.get());
				tabData.accept(MutModItems.DRAGON_SCALE_CLUSTER.get());
				tabData.accept(MutModItems.IRON_BEEF.get());
				tabData.accept(MutModItems.GOLDEN_BEEF.get());
				tabData.accept(MutModItems.DIAMOND_BEEF.get());
				tabData.accept(MutModItems.NETHERITE_BEEF.get());
				tabData.accept(MutModItems.STEEL_BEEF.get());
				tabData.accept(MutModItems.GILDING_BEEF.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_BEEF.get());
				tabData.accept(MutModItems.NETHER_STAR_BEEF.get());
			}).withTabsBefore(MORE_UPGRADE_TMPLATES.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MORE_UPGRADE_TEMPLATE_TOOLS = REGISTRY.register("more_upgrade_template_tools",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.mut.more_upgrade_template_tools")).icon(() -> new ItemStack(MutModItems.BLUE_DIAMOND_PICKAXE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MutModItems.COPPER_SHOVEL.get());
				tabData.accept(MutModItems.COPPER_PICKAXE.get());
				tabData.accept(MutModItems.COPPER_AXE.get());
				tabData.accept(MutModItems.COPPER_HOE.get());
				tabData.accept(MutModItems.EMERALD_SHOVEL.get());
				tabData.accept(MutModItems.EMERALD_PICKAXE.get());
				tabData.accept(MutModItems.EMERALD_AXE.get());
				tabData.accept(MutModItems.EMERALD_HOE.get());
				tabData.accept(MutModItems.STEEL_SHOVEL.get());
				tabData.accept(MutModItems.STEEL_PICKAXE.get());
				tabData.accept(MutModItems.STEEL_AXE.get());
				tabData.accept(MutModItems.STEEL_HOE.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_SHOVEL.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_PICKAXE.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_AXE.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_HOE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_SHOVEL.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_PICKAXE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_AXE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_HOE.get());
				tabData.accept(MutModItems.GILDING_SHOVEL.get());
				tabData.accept(MutModItems.GILDING_PICKAXE.get());
				tabData.accept(MutModItems.GILDING_AXE.get());
				tabData.accept(MutModItems.GILDING_HOE.get());
				tabData.accept(MutModItems.OBSIDIAN_SHOVEL.get());
				tabData.accept(MutModItems.OBSIDIAN_PICKAXE.get());
				tabData.accept(MutModItems.OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.OBSIDIAN_HOE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_SHOVEL.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_PICKAXE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_HOE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_SHOVEL.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_PICKAXE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_HOE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_SHOVEL.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_PICKAXE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_AXE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_HOE.get());
				tabData.accept(MutModItems.DRAGON_SHOVEL.get());
				tabData.accept(MutModItems.DRAGON_PICKAXE.get());
				tabData.accept(MutModItems.DRAGON_AXE.get());
				tabData.accept(MutModItems.DRAGON_HOE.get());
				tabData.accept(MutModItems.IRON_ELYTRA.get());
				tabData.accept(MutModItems.GOLDEN_ELYTRA.get());
				tabData.accept(MutModItems.DIAMOND_ELYTRA.get());
				tabData.accept(MutModItems.NETHERITE_ELYTRA.get());
			}).withSearchBar().withTabsBefore(MORE_UPGRADE_TEMPLATE_EXTRA_ITEMS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MORE_UPGRADE_TEMPLATE_COMBAT_ITEMS = REGISTRY.register("more_upgrade_template_combat_items",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.mut.more_upgrade_template_combat_items")).icon(() -> new ItemStack(MutModItems.BLUE_DIAMOND_SWORD.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MutModItems.COPPER_SWORD.get());
				tabData.accept(MutModItems.COPPER_AXE.get());
				tabData.accept(MutModItems.EMERALD_SWORD.get());
				tabData.accept(MutModItems.EMERALD_AXE.get());
				tabData.accept(MutModItems.STEEL_SWORD.get());
				tabData.accept(MutModItems.STEEL_AXE.get());
				tabData.accept(MutModItems.GILDING_SWORD.get());
				tabData.accept(MutModItems.GILDING_AXE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_SWORD.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_AXE.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_SWORD.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_AXE.get());
				tabData.accept(MutModItems.OBSIDIAN_SWORD.get());
				tabData.accept(MutModItems.OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_SWORD.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_SWORD.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_AXE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_SWORD.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_AXE.get());
				tabData.accept(MutModItems.DRAGON_SWORD.get());
				tabData.accept(MutModItems.DRAGON_AXE.get());
				tabData.accept(MutModItems.WOODEN_MACE.get());
				tabData.accept(MutModItems.IRON_MACE.get());
				tabData.accept(MutModItems.GOLDEN_MACE.get());
				tabData.accept(MutModItems.DIAMOND_MACE.get());
				tabData.accept(MutModItems.NETHERITE_MACE.get());
				tabData.accept(MutModItems.IRON_SHIELD.get());
				tabData.accept(MutModItems.GOLDEN_SHIELD.get());
				tabData.accept(MutModItems.DIAMOND_SHIELD.get());
				tabData.accept(MutModItems.STEEL_SHIELD.get());
				tabData.accept(MutModItems.NETHERITE_SHIELD.get());
				tabData.accept(MutModItems.GILDING_SHIELD.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_SHIELD.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_SHIELD.get());
				tabData.accept(MutModItems.OBSIDIAN_SHIELD.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_SHIELD.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_SHIELD.get());
				tabData.accept(MutModItems.COPPER_HELMET.get());
				tabData.accept(MutModItems.COPPER_CHESTPLATE.get());
				tabData.accept(MutModItems.COPPER_LEGGINGS.get());
				tabData.accept(MutModItems.COPPER_BOOTS.get());
				tabData.accept(MutModItems.GOLDEN_CHAIN_HELMET.get());
				tabData.accept(MutModItems.GOLDEN_CHAIN_CHESTPLATE.get());
				tabData.accept(MutModItems.GOLDEN_CHAIN_LEGGINGS.get());
				tabData.accept(MutModItems.GOLDEN_CHAIN_BOOTS.get());
				tabData.accept(MutModItems.DIAMOND_CHAIN_HELMET.get());
				tabData.accept(MutModItems.DIAMOND_CHAIN_CHESTPLATE.get());
				tabData.accept(MutModItems.DIAMOND_CHAIN_LEGGINGS.get());
				tabData.accept(MutModItems.DIAMOND_CHAIN_BOOTS.get());
				tabData.accept(MutModItems.NETHERITE_CHAIN_HELMET.get());
				tabData.accept(MutModItems.NETHERITE_CHAIN_CHESTPLATE.get());
				tabData.accept(MutModItems.NETHERITE_CHAIN_LEGGINGS.get());
				tabData.accept(MutModItems.NETHERITE_CHAIN_BOOTS.get());
				tabData.accept(MutModItems.EMERALD_ARMOR_HELMET.get());
				tabData.accept(MutModItems.EMERALD_ARMOR_CHESTPLATE.get());
				tabData.accept(MutModItems.EMERALD_ARMOR_LEGGINGS.get());
				tabData.accept(MutModItems.EMERALD_ARMOR_BOOTS.get());
				tabData.accept(MutModItems.STEEL_HELMET.get());
				tabData.accept(MutModItems.STEEL_CHESTPLATE.get());
				tabData.accept(MutModItems.STEEL_LEGGINGS.get());
				tabData.accept(MutModItems.STEEL_BOOTS.get());
				tabData.accept(MutModItems.GILDING_HELMET.get());
				tabData.accept(MutModItems.GILDING_CHESTPLATE.get());
				tabData.accept(MutModItems.GILDING_LEGGINGS.get());
				tabData.accept(MutModItems.GILDING_BOOTS.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_HELMET.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_CHESTPLATE.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_LEGGINGS.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_BOOTS.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_HELMET.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_CHESTPLATE.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_LEGGINGS.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_BOOTS.get());
				tabData.accept(MutModItems.NETHER_STAR_HELMET.get());
				tabData.accept(MutModItems.NETHER_STAR_CHESTPLATE.get());
				tabData.accept(MutModItems.NETHER_STAR_LEGGINGS.get());
				tabData.accept(MutModItems.NETHER_STAR_BOOTS.get());
				tabData.accept(MutModItems.OBSIDIAN_HELMET.get());
				tabData.accept(MutModItems.OBSIDIAN_CHESTPLATE.get());
				tabData.accept(MutModItems.OBSIDIAN_LEGGINGS.get());
				tabData.accept(MutModItems.OBSIDIAN_BOOTS.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_HELMET.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_CHESTPLATE.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_LEGGINGS.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_BOOTS.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_HELMET.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_CHESTPLATE.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_LEGGINGS.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_BOOTS.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_HELMET.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_CHESTPLATE.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_LEGGINGS.get());
				tabData.accept(MutModItems.NETHERITE_REDSTONE_BOOTS.get());
				tabData.accept(MutModItems.DRAGON_HELMET.get());
				tabData.accept(MutModItems.DRAGON_CHESTPLATE.get());
				tabData.accept(MutModItems.DRAGON_LEGGINGS.get());
				tabData.accept(MutModItems.DRAGON_BOOTS.get());
				tabData.accept(MutModItems.DRAGON_CHESTPLATE_ELYTRA.get());
				tabData.accept(MutModItems.IRON_BOW.get());
				tabData.accept(MutModItems.GOLDEN_BOW.get());
				tabData.accept(MutModItems.DIAMOND_BOW.get());
				tabData.accept(MutModItems.NETHERITE_BOW.get());
				tabData.accept(MutModItems.STEEL_BOW.get());
				tabData.accept(MutModItems.GILDING_BOW.get());
				tabData.accept(MutModItems.BLUE_DIAMOND_BOW.get());
				tabData.accept(MutModItems.ADVANCED_STEEL_BOW.get());
				tabData.accept(MutModItems.NETHER_STAR_BOW.get());
				tabData.accept(MutModItems.OBSIDIAN_BOW.get());
				tabData.accept(MutModItems.NETHERITE_OBSIDIAN_BOW.get());
				tabData.accept(MutModItems.CRYING_OBSIDIAN_BOW.get());
			}).withSearchBar().withTabsBefore(MORE_UPGRADE_TEMPLATE_TOOLS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MORE_UPGRADE_TEMPLATE_BLOCKS = REGISTRY.register("more_upgrade_template_blocks",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.mut.more_upgrade_template_blocks")).icon(() -> new ItemStack(MutModBlocks.BLUE_DIAMOND_DEBRIS.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MutModBlocks.STEEL_DEBRIS.get().asItem());
				tabData.accept(MutModBlocks.GILDING_DEBRIS.get().asItem());
				tabData.accept(MutModBlocks.BLUE_DIAMOND_DEBRIS.get().asItem());
				tabData.accept(MutModBlocks.NETHER_DEEP_IRON_ORE_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.STEEL_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.GILDING_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.BLUE_DIAMOND_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.ADVANCED_STEEL_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.OBSIDIAN_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.CRYING_OBSIDIAN_BLOCK.get().asItem());
				tabData.accept(MutModBlocks.TEMPLATE_TRADER_BLOCK.get().asItem());
			}).withTabsBefore(MORE_UPGRADE_TEMPLATE_COMBAT_ITEMS.getId()).build());
}