/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mut.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.mut.procedures.GetPullingProcedure;
import net.mcreator.mut.procedures.GetPullProcedure;
import net.mcreator.mut.item.*;
import net.mcreator.mut.MutMod;

public class MutModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MutMod.MODID);
	public static final DeferredItem<Item> IRON_BOW;
	public static final DeferredItem<Item> STONE_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> IRON_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> DIAMOND_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> IRON_ARMOR_REBUILD_TEMPLATE;
	public static final DeferredItem<Item> DIAMOND_ARMOR_REBUILD_TEMPLATE;
	public static final DeferredItem<Item> STEEL_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> BLUE_DIAMOND_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> OBSIDIAN_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> NETHER_STAR_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> STEEL_DEBRIS;
	public static final DeferredItem<Item> BLUE_DIAMOND_DEBRIS;
	public static final DeferredItem<Item> BLUE_DIAMOND_INGOT;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_SCRAP;
	public static final DeferredItem<Item> DEEP_IRON_SCARP;
	public static final DeferredItem<Item> DEEP_IRON_RAW;
	public static final DeferredItem<Item> ADVANCED_STEEL_INGOT;
	public static final DeferredItem<Item> IRON_BEEF;
	public static final DeferredItem<Item> GOLDEN_BEEF;
	public static final DeferredItem<Item> DIAMOND_BEEF;
	public static final DeferredItem<Item> NETHERITE_BEEF;
	public static final DeferredItem<Item> DIAMOND_BOW;
	public static final DeferredItem<Item> GOLDEN_BOW;
	public static final DeferredItem<Item> NETHERITE_BOW;
	public static final DeferredItem<Item> STEEL_BOW;
	public static final DeferredItem<Item> COPPER_HELMET;
	public static final DeferredItem<Item> COPPER_CHESTPLATE;
	public static final DeferredItem<Item> COPPER_LEGGINGS;
	public static final DeferredItem<Item> COPPER_BOOTS;
	public static final DeferredItem<Item> COPPER_SWORD;
	public static final DeferredItem<Item> COPPER_AXE;
	public static final DeferredItem<Item> COPPER_PICKAXE;
	public static final DeferredItem<Item> COPPER_SHOVEL;
	public static final DeferredItem<Item> COPPER_HOE;
	public static final DeferredItem<Item> STEEL_BEEF;
	public static final DeferredItem<Item> GILDING_BEEF;
	public static final DeferredItem<Item> GILDING_SCRAP;
	public static final DeferredItem<Item> BLUE_DIAMOND_BEEF;
	public static final DeferredItem<Item> NETHER_DEEP_IRON_ORE_BLOCK;
	public static final DeferredItem<Item> STEEL_HELMET;
	public static final DeferredItem<Item> STEEL_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_LEGGINGS;
	public static final DeferredItem<Item> STEEL_BOOTS;
	public static final DeferredItem<Item> STEEL_SWORD;
	public static final DeferredItem<Item> STEEL_PICKAXE;
	public static final DeferredItem<Item> STEEL_AXE;
	public static final DeferredItem<Item> STEEL_SHOVEL;
	public static final DeferredItem<Item> STEEL_HOE;
	public static final DeferredItem<Item> GILDING_BOW;
	public static final DeferredItem<Item> ADVANCED_STEEL_BOW;
	public static final DeferredItem<Item> NETHER_STAR_BOW;
	public static final DeferredItem<Item> ADVANCED_STEEL_HELMET;
	public static final DeferredItem<Item> ADVANCED_STEEL_CHESTPLATE;
	public static final DeferredItem<Item> ADVANCED_STEEL_LEGGINGS;
	public static final DeferredItem<Item> ADVANCED_STEEL_BOOTS;
	public static final DeferredItem<Item> ADVANCED_STEEL_SWORD;
	public static final DeferredItem<Item> ADVANCED_STEEL_AXE;
	public static final DeferredItem<Item> ADVANCED_STEEL_PICKAXE;
	public static final DeferredItem<Item> ADVANCED_STEEL_SHOVEL;
	public static final DeferredItem<Item> ADVANCED_STEEL_HOE;
	public static final DeferredItem<Item> BLUE_DIAMOND_HELMET;
	public static final DeferredItem<Item> BLUE_DIAMOND_CHESTPLATE;
	public static final DeferredItem<Item> BLUE_DIAMOND_LEGGINGS;
	public static final DeferredItem<Item> BLUE_DIAMOND_BOOTS;
	public static final DeferredItem<Item> BLUE_DIAMOND_SWORD;
	public static final DeferredItem<Item> BLUE_DIAMOND_SHOVEL;
	public static final DeferredItem<Item> BLUE_DIAMOND_PICKAXE;
	public static final DeferredItem<Item> BLUE_DIAMOND_AXE;
	public static final DeferredItem<Item> BLUE_DIAMOND_HOE;
	public static final DeferredItem<Item> GILDING_INGOT;
	public static final DeferredItem<Item> GILDING_HELMET;
	public static final DeferredItem<Item> GILDING_CHESTPLATE;
	public static final DeferredItem<Item> GILDING_LEGGINGS;
	public static final DeferredItem<Item> GILDING_BOOTS;
	public static final DeferredItem<Item> GILDING_SWORD;
	public static final DeferredItem<Item> GILDING_SHOVEL;
	public static final DeferredItem<Item> GILDING_PICKAXE;
	public static final DeferredItem<Item> GILDING_AXE;
	public static final DeferredItem<Item> GILDING_HOE;
	public static final DeferredItem<Item> GILDING_DEBRIS;
	public static final DeferredItem<Item> STEEL_SHIELD;
	public static final DeferredItem<Item> IRON_SHIELD;
	public static final DeferredItem<Item> DIAMOND_SHIELD;
	public static final DeferredItem<Item> GOLDEN_SHIELD;
	public static final DeferredItem<Item> NETHERITE_SHIELD;
	public static final DeferredItem<Item> EMERALD_ARMOR_HELMET;
	public static final DeferredItem<Item> EMERALD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EMERALD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EMERALD_ARMOR_BOOTS;
	public static final DeferredItem<Item> EMERALD_SWORD;
	public static final DeferredItem<Item> EMERALD_SHOVEL;
	public static final DeferredItem<Item> EMERALD_PICKAXE;
	public static final DeferredItem<Item> EMERALD_AXE;
	public static final DeferredItem<Item> EMERALD_HOE;
	public static final DeferredItem<Item> OBSIDIAN_HELMET;
	public static final DeferredItem<Item> OBSIDIAN_CHESTPLATE;
	public static final DeferredItem<Item> OBSIDIAN_LEGGINGS;
	public static final DeferredItem<Item> OBSIDIAN_BOOTS;
	public static final DeferredItem<Item> OBSIDIAN_SWORD;
	public static final DeferredItem<Item> OBSIDIAN_SHOVEL;
	public static final DeferredItem<Item> OBSIDIAN_PICKAXE;
	public static final DeferredItem<Item> OBSIDIAN_AXE;
	public static final DeferredItem<Item> OBSIDIAN_HOE;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_HELMET;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_CHESTPLATE;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_LEGGINGS;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_BOOTS;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_INGOT;
	public static final DeferredItem<Item> OBSIDIAN_INGOT;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_SWORD;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_SHOVEL;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_PICKAXE;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_AXE;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_HOE;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_HELMET;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_CHESTPLATE;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_LEGGINGS;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_BOOTS;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_SWORD;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_SHOVEL;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_PICKAXE;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_AXE;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_HOE;
	public static final DeferredItem<Item> BLUE_DIAMOND_BOW;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_HELMET;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_CHESTPLATE;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_LEGGINGS;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_BOOTS;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_SWORD;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_SHOVEL;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_PICKAXE;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_AXE;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_HOE;
	public static final DeferredItem<Item> DRAGON_HELMET;
	public static final DeferredItem<Item> DRAGON_CHESTPLATE;
	public static final DeferredItem<Item> DRAGON_LEGGINGS;
	public static final DeferredItem<Item> DRAGON_BOOTS;
	public static final DeferredItem<Item> DRAGON_SWORD;
	public static final DeferredItem<Item> DRAGON_SHOVEL;
	public static final DeferredItem<Item> DRAGON_PICKAXE;
	public static final DeferredItem<Item> DRAGON_AXE;
	public static final DeferredItem<Item> DRAGON_HOE;
	public static final DeferredItem<Item> OBSIDIAN_BOW;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_BOW;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_BOW;
	public static final DeferredItem<Item> IRON_MACE;
	public static final DeferredItem<Item> WOODEN_MACE;
	public static final DeferredItem<Item> DIAMOND_MACE;
	public static final DeferredItem<Item> GOLDEN_MACE;
	public static final DeferredItem<Item> NETHERITE_MACE;
	public static final DeferredItem<Item> DIAMOND_CHAIN_HELMET;
	public static final DeferredItem<Item> DIAMOND_CHAIN_CHESTPLATE;
	public static final DeferredItem<Item> DIAMOND_CHAIN_LEGGINGS;
	public static final DeferredItem<Item> DIAMOND_CHAIN_BOOTS;
	public static final DeferredItem<Item> GOLDEN_CHAIN_HELMET;
	public static final DeferredItem<Item> GOLDEN_CHAIN_CHESTPLATE;
	public static final DeferredItem<Item> GOLDEN_CHAIN_LEGGINGS;
	public static final DeferredItem<Item> GOLDEN_CHAIN_BOOTS;
	public static final DeferredItem<Item> NETHERITE_CHAIN_HELMET;
	public static final DeferredItem<Item> NETHERITE_CHAIN_CHESTPLATE;
	public static final DeferredItem<Item> NETHERITE_CHAIN_LEGGINGS;
	public static final DeferredItem<Item> NETHERITE_CHAIN_BOOTS;
	public static final DeferredItem<Item> GILDING_SHIELD;
	public static final DeferredItem<Item> BLUE_DIAMOND_SHIELD;
	public static final DeferredItem<Item> OBSIDIAN_SHIELD;
	public static final DeferredItem<Item> NETHERITE_OBSIDIAN_SHIELD;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_SHIELD;
	public static final DeferredItem<Item> GILDING_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> DRAGON_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> DRAGON_SCALE_CLUSTER;
	public static final DeferredItem<Item> STEEL_BLOCK;
	public static final DeferredItem<Item> GILDING_BLOCK;
	public static final DeferredItem<Item> BLUE_DIAMOND_BLOCK;
	public static final DeferredItem<Item> ADVANCED_STEEL_BLOCK;
	public static final DeferredItem<Item> OBSIDIAN_BLOCK;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_BLOCK;
	public static final DeferredItem<Item> NETHER_STAR_BEEF;
	public static final DeferredItem<Item> NETHER_STAR_HELMET;
	public static final DeferredItem<Item> NETHER_STAR_CHESTPLATE;
	public static final DeferredItem<Item> NETHER_STAR_LEGGINGS;
	public static final DeferredItem<Item> NETHER_STAR_BOOTS;
	public static final DeferredItem<Item> TEMPLATE_TRADER_BLOCK;
	public static final DeferredItem<Item> IRON_ELYTRA;
	public static final DeferredItem<Item> GOLDEN_ELYTRA;
	public static final DeferredItem<Item> DIAMOND_ELYTRA;
	public static final DeferredItem<Item> NETHERITE_ELYTRA;
	public static final DeferredItem<Item> ADVANCED_STEEL_SHIELD;
	public static final DeferredItem<Item> GOLD_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> BLUE_DIAMOND_SCRAP;
	public static final DeferredItem<Item> DRAGON_CHESTPLATE_ELYTRA;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> NETHERITE_REDSTONE_INGOT;
	static {
		IRON_BOW = REGISTRY.register("iron_bow", IronBowItem::new);
		STONE_UPGRADE_TEMPLATE = REGISTRY.register("stone_upgrade_template", StoneUpgradeTemplateItem::new);
		IRON_UPGRADE_TEMPLATE = REGISTRY.register("iron_upgrade_template", IronUpgradeTemplateItem::new);
		DIAMOND_UPGRADE_TEMPLATE = REGISTRY.register("diamond_upgrade_template", DiamondUpgradeTemplateItem::new);
		IRON_ARMOR_REBUILD_TEMPLATE = REGISTRY.register("iron_armor_rebuild_template", IronArmorRebuildTemplateItem::new);
		DIAMOND_ARMOR_REBUILD_TEMPLATE = REGISTRY.register("diamond_armor_rebuild_template", DiamondArmorRebuildTemplateItem::new);
		STEEL_UPGRADE_TEMPLATE = REGISTRY.register("steel_upgrade_template", SteelUpgradeTemplateItem::new);
		BLUE_DIAMOND_UPGRADE_TEMPLATE = REGISTRY.register("blue_diamond_upgrade_template", BlueDiamondUpgradeTemplateItem::new);
		OBSIDIAN_UPGRADE_TEMPLATE = REGISTRY.register("obsidian_upgrade_template", ObsidianUpgradeTemplateItem::new);
		NETHERITE_OBSIDIAN_UPGRADE_TEMPLATE = REGISTRY.register("netherite_obsidian_upgrade_template", NetheriteObsidianUpgradeTemplateItem::new);
		NETHER_STAR_UPGRADE_TEMPLATE = REGISTRY.register("nether_star_upgrade_template", NetherStarUpgradeTemplateItem::new);
		STEEL_DEBRIS = block(MutModBlocks.STEEL_DEBRIS, new Item.Properties().rarity(Rarity.RARE).fireResistant());
		BLUE_DIAMOND_DEBRIS = block(MutModBlocks.BLUE_DIAMOND_DEBRIS, new Item.Properties().rarity(Rarity.RARE).fireResistant());
		BLUE_DIAMOND_INGOT = REGISTRY.register("blue_diamond_ingot", BlueDiamondIngotItem::new);
		STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
		STEEL_SCRAP = REGISTRY.register("steel_scrap", SteelScrapItem::new);
		DEEP_IRON_SCARP = REGISTRY.register("deep_iron_scarp", DeepIronScarpItem::new);
		DEEP_IRON_RAW = REGISTRY.register("deep_iron_raw", DeepIronRawItem::new);
		ADVANCED_STEEL_INGOT = REGISTRY.register("advanced_steel_ingot", AdvancedSteelIngotItem::new);
		IRON_BEEF = REGISTRY.register("iron_beef", IronBeefItem::new);
		GOLDEN_BEEF = REGISTRY.register("golden_beef", GoldenBeefItem::new);
		DIAMOND_BEEF = REGISTRY.register("diamond_beef", DiamondBeefItem::new);
		NETHERITE_BEEF = REGISTRY.register("netherite_beef", NetheriteBeefItem::new);
		DIAMOND_BOW = REGISTRY.register("diamond_bow", DiamondBowItem::new);
		GOLDEN_BOW = REGISTRY.register("golden_bow", GoldenBowItem::new);
		NETHERITE_BOW = REGISTRY.register("netherite_bow", NetheriteBowItem::new);
		STEEL_BOW = REGISTRY.register("steel_bow", SteelBowItem::new);
		COPPER_HELMET = REGISTRY.register("copper_helmet", CopperItem.Helmet::new);
		COPPER_CHESTPLATE = REGISTRY.register("copper_chestplate", CopperItem.Chestplate::new);
		COPPER_LEGGINGS = REGISTRY.register("copper_leggings", CopperItem.Leggings::new);
		COPPER_BOOTS = REGISTRY.register("copper_boots", CopperItem.Boots::new);
		COPPER_SWORD = REGISTRY.register("copper_sword", CopperSwordItem::new);
		COPPER_AXE = REGISTRY.register("copper_axe", CopperAxeItem::new);
		COPPER_PICKAXE = REGISTRY.register("copper_pickaxe", CopperPickaxeItem::new);
		COPPER_SHOVEL = REGISTRY.register("copper_shovel", CopperShovelItem::new);
		COPPER_HOE = REGISTRY.register("copper_hoe", CopperHoeItem::new);
		STEEL_BEEF = REGISTRY.register("steel_beef", SteelBeefItem::new);
		GILDING_BEEF = REGISTRY.register("gilding_beef", GildingBeefItem::new);
		GILDING_SCRAP = REGISTRY.register("gilding_scrap", GildingScrapItem::new);
		BLUE_DIAMOND_BEEF = REGISTRY.register("blue_diamond_beef", BlueDiamondBeefItem::new);
		NETHER_DEEP_IRON_ORE_BLOCK = block(MutModBlocks.NETHER_DEEP_IRON_ORE_BLOCK, new Item.Properties().fireResistant());
		STEEL_HELMET = REGISTRY.register("steel_helmet", SteelItem.Helmet::new);
		STEEL_CHESTPLATE = REGISTRY.register("steel_chestplate", SteelItem.Chestplate::new);
		STEEL_LEGGINGS = REGISTRY.register("steel_leggings", SteelItem.Leggings::new);
		STEEL_BOOTS = REGISTRY.register("steel_boots", SteelItem.Boots::new);
		STEEL_SWORD = REGISTRY.register("steel_sword", SteelSwordItem::new);
		STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", SteelPickaxeItem::new);
		STEEL_AXE = REGISTRY.register("steel_axe", SteelAxeItem::new);
		STEEL_SHOVEL = REGISTRY.register("steel_shovel", SteelShovelItem::new);
		STEEL_HOE = REGISTRY.register("steel_hoe", SteelHoeItem::new);
		GILDING_BOW = REGISTRY.register("gilding_bow", GildingBowItem::new);
		ADVANCED_STEEL_BOW = REGISTRY.register("advanced_steel_bow", AdvancedSteelBowItem::new);
		NETHER_STAR_BOW = REGISTRY.register("nether_star_bow", NetherStarBowItem::new);
		ADVANCED_STEEL_HELMET = REGISTRY.register("advanced_steel_helmet", AdvancedSteelItem.Helmet::new);
		ADVANCED_STEEL_CHESTPLATE = REGISTRY.register("advanced_steel_chestplate", AdvancedSteelItem.Chestplate::new);
		ADVANCED_STEEL_LEGGINGS = REGISTRY.register("advanced_steel_leggings", AdvancedSteelItem.Leggings::new);
		ADVANCED_STEEL_BOOTS = REGISTRY.register("advanced_steel_boots", AdvancedSteelItem.Boots::new);
		ADVANCED_STEEL_SWORD = REGISTRY.register("advanced_steel_sword", AdvancedSteelSwordItem::new);
		ADVANCED_STEEL_AXE = REGISTRY.register("advanced_steel_axe", AdvancedSteelAxeItem::new);
		ADVANCED_STEEL_PICKAXE = REGISTRY.register("advanced_steel_pickaxe", AdvancedSteelPickaxeItem::new);
		ADVANCED_STEEL_SHOVEL = REGISTRY.register("advanced_steel_shovel", AdvancedSteelShovelItem::new);
		ADVANCED_STEEL_HOE = REGISTRY.register("advanced_steel_hoe", AdvancedSteelHoeItem::new);
		BLUE_DIAMOND_HELMET = REGISTRY.register("blue_diamond_helmet", BlueDiamondItem.Helmet::new);
		BLUE_DIAMOND_CHESTPLATE = REGISTRY.register("blue_diamond_chestplate", BlueDiamondItem.Chestplate::new);
		BLUE_DIAMOND_LEGGINGS = REGISTRY.register("blue_diamond_leggings", BlueDiamondItem.Leggings::new);
		BLUE_DIAMOND_BOOTS = REGISTRY.register("blue_diamond_boots", BlueDiamondItem.Boots::new);
		BLUE_DIAMOND_SWORD = REGISTRY.register("blue_diamond_sword", BlueDiamondSwordItem::new);
		BLUE_DIAMOND_SHOVEL = REGISTRY.register("blue_diamond_shovel", BlueDiamondShovelItem::new);
		BLUE_DIAMOND_PICKAXE = REGISTRY.register("blue_diamond_pickaxe", BlueDiamondPickaxeItem::new);
		BLUE_DIAMOND_AXE = REGISTRY.register("blue_diamond_axe", BlueDiamondAxeItem::new);
		BLUE_DIAMOND_HOE = REGISTRY.register("blue_diamond_hoe", BlueDiamondHoeItem::new);
		GILDING_INGOT = REGISTRY.register("gilding_ingot", GildingIngotItem::new);
		GILDING_HELMET = REGISTRY.register("gilding_helmet", GildingItem.Helmet::new);
		GILDING_CHESTPLATE = REGISTRY.register("gilding_chestplate", GildingItem.Chestplate::new);
		GILDING_LEGGINGS = REGISTRY.register("gilding_leggings", GildingItem.Leggings::new);
		GILDING_BOOTS = REGISTRY.register("gilding_boots", GildingItem.Boots::new);
		GILDING_SWORD = REGISTRY.register("gilding_sword", GildingSwordItem::new);
		GILDING_SHOVEL = REGISTRY.register("gilding_shovel", GildingShovelItem::new);
		GILDING_PICKAXE = REGISTRY.register("gilding_pickaxe", GildingPickaxeItem::new);
		GILDING_AXE = REGISTRY.register("gilding_axe", GildingAxeItem::new);
		GILDING_HOE = REGISTRY.register("gilding_hoe", GildingHoeItem::new);
		GILDING_DEBRIS = block(MutModBlocks.GILDING_DEBRIS, new Item.Properties().rarity(Rarity.RARE).fireResistant());
		STEEL_SHIELD = REGISTRY.register("steel_shield", SteelShieldItem::new);
		IRON_SHIELD = REGISTRY.register("iron_shield", IronShieldItem::new);
		DIAMOND_SHIELD = REGISTRY.register("diamond_shield", DiamondShieldItem::new);
		GOLDEN_SHIELD = REGISTRY.register("golden_shield", GoldenShieldItem::new);
		NETHERITE_SHIELD = REGISTRY.register("netherite_shield", NetheriteShieldItem::new);
		EMERALD_ARMOR_HELMET = REGISTRY.register("emerald_armor_helmet", EmeraldArmorItem.Helmet::new);
		EMERALD_ARMOR_CHESTPLATE = REGISTRY.register("emerald_armor_chestplate", EmeraldArmorItem.Chestplate::new);
		EMERALD_ARMOR_LEGGINGS = REGISTRY.register("emerald_armor_leggings", EmeraldArmorItem.Leggings::new);
		EMERALD_ARMOR_BOOTS = REGISTRY.register("emerald_armor_boots", EmeraldArmorItem.Boots::new);
		EMERALD_SWORD = REGISTRY.register("emerald_sword", EmeraldSwordItem::new);
		EMERALD_SHOVEL = REGISTRY.register("emerald_shovel", EmeraldShovelItem::new);
		EMERALD_PICKAXE = REGISTRY.register("emerald_pickaxe", EmeraldPickaxeItem::new);
		EMERALD_AXE = REGISTRY.register("emerald_axe", EmeraldAxeItem::new);
		EMERALD_HOE = REGISTRY.register("emerald_hoe", EmeraldHoeItem::new);
		OBSIDIAN_HELMET = REGISTRY.register("obsidian_helmet", ObsidianItem.Helmet::new);
		OBSIDIAN_CHESTPLATE = REGISTRY.register("obsidian_chestplate", ObsidianItem.Chestplate::new);
		OBSIDIAN_LEGGINGS = REGISTRY.register("obsidian_leggings", ObsidianItem.Leggings::new);
		OBSIDIAN_BOOTS = REGISTRY.register("obsidian_boots", ObsidianItem.Boots::new);
		OBSIDIAN_SWORD = REGISTRY.register("obsidian_sword", ObsidianSwordItem::new);
		OBSIDIAN_SHOVEL = REGISTRY.register("obsidian_shovel", ObsidianShovelItem::new);
		OBSIDIAN_PICKAXE = REGISTRY.register("obsidian_pickaxe", ObsidianPickaxeItem::new);
		OBSIDIAN_AXE = REGISTRY.register("obsidian_axe", ObsidianAxeItem::new);
		OBSIDIAN_HOE = REGISTRY.register("obsidian_hoe", ObsidianHoeItem::new);
		NETHERITE_OBSIDIAN_HELMET = REGISTRY.register("netherite_obsidian_helmet", NetheriteObsidianItem.Helmet::new);
		NETHERITE_OBSIDIAN_CHESTPLATE = REGISTRY.register("netherite_obsidian_chestplate", NetheriteObsidianItem.Chestplate::new);
		NETHERITE_OBSIDIAN_LEGGINGS = REGISTRY.register("netherite_obsidian_leggings", NetheriteObsidianItem.Leggings::new);
		NETHERITE_OBSIDIAN_BOOTS = REGISTRY.register("netherite_obsidian_boots", NetheriteObsidianItem.Boots::new);
		CRYING_OBSIDIAN_INGOT = REGISTRY.register("crying_obsidian_ingot", CryingObsidianIngotItem::new);
		OBSIDIAN_INGOT = REGISTRY.register("obsidian_ingot", ObsidianIngotItem::new);
		NETHERITE_OBSIDIAN_SWORD = REGISTRY.register("netherite_obsidian_sword", NetheriteObsidianSwordItem::new);
		NETHERITE_OBSIDIAN_SHOVEL = REGISTRY.register("netherite_obsidian_shovel", NetheriteObsidianShovelItem::new);
		NETHERITE_OBSIDIAN_PICKAXE = REGISTRY.register("netherite_obsidian_pickaxe", NetheriteObsidianPickaxeItem::new);
		NETHERITE_OBSIDIAN_AXE = REGISTRY.register("netherite_obsidian_axe", NetheriteObsidianAxeItem::new);
		NETHERITE_OBSIDIAN_HOE = REGISTRY.register("netherite_obsidian_hoe", NetheriteObsidianHoeItem::new);
		CRYING_OBSIDIAN_HELMET = REGISTRY.register("crying_obsidian_helmet", CryingObsidianItem.Helmet::new);
		CRYING_OBSIDIAN_CHESTPLATE = REGISTRY.register("crying_obsidian_chestplate", CryingObsidianItem.Chestplate::new);
		CRYING_OBSIDIAN_LEGGINGS = REGISTRY.register("crying_obsidian_leggings", CryingObsidianItem.Leggings::new);
		CRYING_OBSIDIAN_BOOTS = REGISTRY.register("crying_obsidian_boots", CryingObsidianItem.Boots::new);
		CRYING_OBSIDIAN_SWORD = REGISTRY.register("crying_obsidian_sword", CryingObsidianSwordItem::new);
		CRYING_OBSIDIAN_SHOVEL = REGISTRY.register("crying_obsidian_shovel", CryingObsidianShovelItem::new);
		CRYING_OBSIDIAN_PICKAXE = REGISTRY.register("crying_obsidian_pickaxe", CryingObsidianPickaxeItem::new);
		CRYING_OBSIDIAN_AXE = REGISTRY.register("crying_obsidian_axe", CryingObsidianAxeItem::new);
		CRYING_OBSIDIAN_HOE = REGISTRY.register("crying_obsidian_hoe", CryingObsidianHoeItem::new);
		BLUE_DIAMOND_BOW = REGISTRY.register("blue_diamond_bow", BlueDiamondBowItem::new);
		NETHERITE_REDSTONE_HELMET = REGISTRY.register("netherite_redstone_helmet", NetheriteRedstoneItem.Helmet::new);
		NETHERITE_REDSTONE_CHESTPLATE = REGISTRY.register("netherite_redstone_chestplate", NetheriteRedstoneItem.Chestplate::new);
		NETHERITE_REDSTONE_LEGGINGS = REGISTRY.register("netherite_redstone_leggings", NetheriteRedstoneItem.Leggings::new);
		NETHERITE_REDSTONE_BOOTS = REGISTRY.register("netherite_redstone_boots", NetheriteRedstoneItem.Boots::new);
		NETHERITE_REDSTONE_SWORD = REGISTRY.register("netherite_redstone_sword", NetheriteRedstoneSwordItem::new);
		NETHERITE_REDSTONE_SHOVEL = REGISTRY.register("netherite_redstone_shovel", NetheriteRedstoneShovelItem::new);
		NETHERITE_REDSTONE_PICKAXE = REGISTRY.register("netherite_redstone_pickaxe", NetheriteRedstonePickaxeItem::new);
		NETHERITE_REDSTONE_AXE = REGISTRY.register("netherite_redstone_axe", NetheriteRedstoneAxeItem::new);
		NETHERITE_REDSTONE_HOE = REGISTRY.register("netherite_redstone_hoe", NetheriteRedstoneHoeItem::new);
		DRAGON_HELMET = REGISTRY.register("dragon_helmet", DragonItem.Helmet::new);
		DRAGON_CHESTPLATE = REGISTRY.register("dragon_chestplate", DragonItem.Chestplate::new);
		DRAGON_LEGGINGS = REGISTRY.register("dragon_leggings", DragonItem.Leggings::new);
		DRAGON_BOOTS = REGISTRY.register("dragon_boots", DragonItem.Boots::new);
		DRAGON_SWORD = REGISTRY.register("dragon_sword", DragonSwordItem::new);
		DRAGON_SHOVEL = REGISTRY.register("dragon_shovel", DragonShovelItem::new);
		DRAGON_PICKAXE = REGISTRY.register("dragon_pickaxe", DragonPickaxeItem::new);
		DRAGON_AXE = REGISTRY.register("dragon_axe", DragonAxeItem::new);
		DRAGON_HOE = REGISTRY.register("dragon_hoe", DragonHoeItem::new);
		OBSIDIAN_BOW = REGISTRY.register("obsidian_bow", ObsidianBowItem::new);
		NETHERITE_OBSIDIAN_BOW = REGISTRY.register("netherite_obsidian_bow", NetheriteObsidianBowItem::new);
		CRYING_OBSIDIAN_BOW = REGISTRY.register("crying_obsidian_bow", CryingObsidianBowItem::new);
		IRON_MACE = REGISTRY.register("iron_mace", IronMaceItem::new);
		WOODEN_MACE = REGISTRY.register("wooden_mace", WoodenMaceItem::new);
		DIAMOND_MACE = REGISTRY.register("diamond_mace", DiamondMaceItem::new);
		GOLDEN_MACE = REGISTRY.register("golden_mace", GoldenMaceItem::new);
		NETHERITE_MACE = REGISTRY.register("netherite_mace", NetheriteMaceItem::new);
		DIAMOND_CHAIN_HELMET = REGISTRY.register("diamond_chain_helmet", DiamondChainItem.Helmet::new);
		DIAMOND_CHAIN_CHESTPLATE = REGISTRY.register("diamond_chain_chestplate", DiamondChainItem.Chestplate::new);
		DIAMOND_CHAIN_LEGGINGS = REGISTRY.register("diamond_chain_leggings", DiamondChainItem.Leggings::new);
		DIAMOND_CHAIN_BOOTS = REGISTRY.register("diamond_chain_boots", DiamondChainItem.Boots::new);
		GOLDEN_CHAIN_HELMET = REGISTRY.register("golden_chain_helmet", GoldenChainItem.Helmet::new);
		GOLDEN_CHAIN_CHESTPLATE = REGISTRY.register("golden_chain_chestplate", GoldenChainItem.Chestplate::new);
		GOLDEN_CHAIN_LEGGINGS = REGISTRY.register("golden_chain_leggings", GoldenChainItem.Leggings::new);
		GOLDEN_CHAIN_BOOTS = REGISTRY.register("golden_chain_boots", GoldenChainItem.Boots::new);
		NETHERITE_CHAIN_HELMET = REGISTRY.register("netherite_chain_helmet", NetheriteChainItem.Helmet::new);
		NETHERITE_CHAIN_CHESTPLATE = REGISTRY.register("netherite_chain_chestplate", NetheriteChainItem.Chestplate::new);
		NETHERITE_CHAIN_LEGGINGS = REGISTRY.register("netherite_chain_leggings", NetheriteChainItem.Leggings::new);
		NETHERITE_CHAIN_BOOTS = REGISTRY.register("netherite_chain_boots", NetheriteChainItem.Boots::new);
		GILDING_SHIELD = REGISTRY.register("gilding_shield", GildingShieldItem::new);
		BLUE_DIAMOND_SHIELD = REGISTRY.register("blue_diamond_shield", BlueDiamondShieldItem::new);
		OBSIDIAN_SHIELD = REGISTRY.register("obsidian_shield", ObsidianShieldItem::new);
		NETHERITE_OBSIDIAN_SHIELD = REGISTRY.register("netherite_obsidian_shield", NetheriteObsidianShieldItem::new);
		CRYING_OBSIDIAN_SHIELD = REGISTRY.register("crying_obsidian_shield", CryingObsidianShieldItem::new);
		GILDING_UPGRADE_TEMPLATE = REGISTRY.register("gilding_upgrade_template", GildingUpgradeTemplateItem::new);
		CRYING_OBSIDIAN_UPGRADE_TEMPLATE = REGISTRY.register("crying_obsidian_upgrade_template", CryingObsidianUpgradeTemplateItem::new);
		DRAGON_UPGRADE_TEMPLATE = REGISTRY.register("dragon_upgrade_template", DragonUpgradeTemplateItem::new);
		DRAGON_SCALE_CLUSTER = REGISTRY.register("dragon_scale_cluster", DragonScaleClusterItem::new);
		STEEL_BLOCK = block(MutModBlocks.STEEL_BLOCK, new Item.Properties().fireResistant());
		GILDING_BLOCK = block(MutModBlocks.GILDING_BLOCK, new Item.Properties().fireResistant());
		BLUE_DIAMOND_BLOCK = block(MutModBlocks.BLUE_DIAMOND_BLOCK, new Item.Properties().fireResistant());
		ADVANCED_STEEL_BLOCK = block(MutModBlocks.ADVANCED_STEEL_BLOCK, new Item.Properties().fireResistant());
		OBSIDIAN_BLOCK = block(MutModBlocks.OBSIDIAN_BLOCK, new Item.Properties().fireResistant());
		CRYING_OBSIDIAN_BLOCK = block(MutModBlocks.CRYING_OBSIDIAN_BLOCK, new Item.Properties().fireResistant());
		NETHER_STAR_BEEF = REGISTRY.register("nether_star_beef", NetherStarBeefItem::new);
		NETHER_STAR_HELMET = REGISTRY.register("nether_star_helmet", NetherStarItem.Helmet::new);
		NETHER_STAR_CHESTPLATE = REGISTRY.register("nether_star_chestplate", NetherStarItem.Chestplate::new);
		NETHER_STAR_LEGGINGS = REGISTRY.register("nether_star_leggings", NetherStarItem.Leggings::new);
		NETHER_STAR_BOOTS = REGISTRY.register("nether_star_boots", NetherStarItem.Boots::new);
		TEMPLATE_TRADER_BLOCK = block(MutModBlocks.TEMPLATE_TRADER_BLOCK, new Item.Properties().fireResistant());
		IRON_ELYTRA = REGISTRY.register("iron_elytra", IronElytraItem::new);
		GOLDEN_ELYTRA = REGISTRY.register("golden_elytra", GoldenElytraItem::new);
		DIAMOND_ELYTRA = REGISTRY.register("diamond_elytra", DiamondElytraItem::new);
		NETHERITE_ELYTRA = REGISTRY.register("netherite_elytra", NetheriteElytraItem::new);
		ADVANCED_STEEL_SHIELD = REGISTRY.register("advanced_steel_shield", AdvancedSteelShieldItem::new);
		GOLD_UPGRADE_TEMPLATE = REGISTRY.register("gold_upgrade_template", GoldUpgradeTemplateItem::new);
		BLUE_DIAMOND_SCRAP = REGISTRY.register("blue_diamond_scrap", BlueDiamondScrapItem::new);
		DRAGON_CHESTPLATE_ELYTRA = REGISTRY.register("dragon_chestplate_elytra", DragonChestplateElytraItem::new);
		NETHERITE_REDSTONE_UPGRADE_TEMPLATE = REGISTRY.register("netherite_redstone_upgrade_template", NetheriteRedstoneUpgradeTemplateItem::new);
		NETHERITE_REDSTONE_INGOT = REGISTRY.register("netherite_redstone_ingot", NetheriteRedstoneIngotItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(IRON_BOW.get(), ResourceLocation.parse("mut:iron_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(IRON_BOW.get(), ResourceLocation.parse("mut:iron_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(DIAMOND_BOW.get(), ResourceLocation.parse("mut:diamond_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(DIAMOND_BOW.get(), ResourceLocation.parse("mut:diamond_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(GOLDEN_BOW.get(), ResourceLocation.parse("mut:golden_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(GOLDEN_BOW.get(), ResourceLocation.parse("mut:golden_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(NETHERITE_BOW.get(), ResourceLocation.parse("mut:netherite_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(NETHERITE_BOW.get(), ResourceLocation.parse("mut:netherite_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(STEEL_BOW.get(), ResourceLocation.parse("mut:steel_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(STEEL_BOW.get(), ResourceLocation.parse("mut:steel_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(GILDING_BOW.get(), ResourceLocation.parse("mut:gilding_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(GILDING_BOW.get(), ResourceLocation.parse("mut:gilding_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(ADVANCED_STEEL_BOW.get(), ResourceLocation.parse("mut:advanced_steel_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(ADVANCED_STEEL_BOW.get(), ResourceLocation.parse("mut:advanced_steel_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(NETHER_STAR_BOW.get(), ResourceLocation.parse("mut:nether_star_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(NETHER_STAR_BOW.get(), ResourceLocation.parse("mut:nether_star_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(STEEL_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(IRON_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(DIAMOND_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(GOLDEN_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(NETHERITE_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(BLUE_DIAMOND_BOW.get(), ResourceLocation.parse("mut:blue_diamond_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(BLUE_DIAMOND_BOW.get(), ResourceLocation.parse("mut:blue_diamond_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:obsidian_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:obsidian_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(NETHERITE_OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:netherite_obsidian_bow_pulling"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(NETHERITE_OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:netherite_obsidian_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(CRYING_OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:crying_obsidian_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(CRYING_OBSIDIAN_BOW.get(), ResourceLocation.parse("mut:crying_obsidian_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullProcedure.execute(entity));
				ItemProperties.register(GILDING_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(BLUE_DIAMOND_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(OBSIDIAN_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(NETHERITE_OBSIDIAN_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(CRYING_OBSIDIAN_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(ADVANCED_STEEL_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
			});
		}
	}
}